### ISSUE TITLE
Help needed for Server

### ISSUE THREAD

**Issue by meetec** [torehc/carontepass-v2#7]
Hi,
I what to replicate this project and I am having trouble.
I have esp8266mod, rc522 and made virtual Linux for server.
In your read me I can't find help on making server.
Is there some steps that can I follow?

Thanks

**Comment by meetec** [comment]
(venv) osboxes@osboxes:~/carontepass/carontepass$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/osboxes/carontepass/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/osboxes/carontepass/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/osboxes/carontepass/venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/osboxes/carontepass/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/osboxes/carontepass/venv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/osboxes/carontepass/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/osboxes/carontepass/carontepass/access/models.py", line 5, in <module>
    from telegram_group import send_group_msg, send_simple_msg, send_log_msg
ImportError: No module named 'telegram_group'

**Comment by torehc** [comment]
Try Python2.7

**Comment by meetec** [comment]
Thanks,
Yes, it's only work on Python 2.7

Now I have problem with uploading to esp8266 CP2102
I am getting ...
...
exit status 1
redefinition of 'const char* ssid'

**Comment by meetec** [comment]
Done with that problem.
When I start caronte-esp8266.ino it's load caronte-esp8266-two-rfid.ino two.
You can't have both upload at same time.
Just copy code from caronte-esp8266.ino and make new project. That's it

**Comment by meetec** [comment]
Now I have this error when I do "puthon manage.py migrate"
osboxes@osboxes:~/carontepass-v2/web/carontepass$ python manage.py migrate
Operations to perform:
  Apply all migrations: access, admin, contenttypes, auth, sessions
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying access.0001_initial... OK
  Applying access.0002_user... OK
  Applying access.0003_message... OK
  Applying access.0004_device_log_payment... OK
  Applying access.0005_auto_20151110_1730... OK
  Applying access.0006_auto_20151110_1810... OK
  Applying access.0007_auto_20151111_1248... OK
  Applying access.0008_auto_20151111_1250... OK
  Applying access.0009_auto_20151116_2257... OK
  Applying access.0010_auto_20151116_2306... OK
  Applying access.0011_log_user_in... OK
  Applying access.0012_auto_20151221_1239... OK
  Applying access.0013_auto_20160203_1405... OK
  Applying access.0014_auto_20160228_2223... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying sessions.0001_initial... OK
Exception in thread WorkerThread2 (most likely raised during interpreter shutdown):Exception in thread WorkerThread1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/osboxes/.local/lib/python2.7/site-packages/telebot/util.py", line 61, in run

<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/osboxes/.local/lib/python2.7/site-packages/telebot/util.py", line 61, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
osboxes@osboxes:~/carontepass-v2/web/carontepass$
